using Swashbuckle.AspNetCore.SwaggerGen;

namespace DiGi.WebAPI.Interfaces
{
    /// <summary>
    /// Defines a filter for modifying the OpenAPI schema generated by Swagger.
    /// </summary>
    public interface IWebAPISchemaFilter : ISchemaFilter
    {
    }
}
