<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<LangVersion>latest</LangVersion>
	<OutputPath>..\bin\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	<Nullable>enable</Nullable>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DiGi.Core">
      <HintPath>..\..\DiGi.Core\bin\DiGi.Core.dll</HintPath>
    </Reference>
    <Reference Include="DiGi.Serilog">
      <HintPath>..\..\DiGi.Serilog\bin\DiGi.Serilog.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
